name: Publish site
on:
  release:
    types: 
      - created
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: "Build UI5"
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: "Install ui5 command line tooling"
        run: npm i -g @ui5/cli
      - name: "Npm install"
        run: npm i
      - name: "Build"
        run: npm run build:uimodule
      - name: S3 upload
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'uimodule/dist'      # optional: defaults to entire repository